### ISSUE TITLE
Problem when switching between different Forge Profiles [WIN]

### ISSUE THREAD

**Issue by jgonfer** [ZENZO-Ecosystem/zenzo-forge#7]
### Describe the issue
I'm trying to switch between different Forge Profiles (`CoinDreams`, `Josep`) by changing the content default `config.json` file with the content of my existing profiles created with previous versions of Forge. When I try to use the configuration of those profiles, it isn't recognized and then I need to select the `Setup` button. Once I select `Setup`, the `config.json` file is updated and the Forge app loads one of my existing profiles: `CoinDreams`. This happens always that I select `Setup`.

### Can you reliably reproduce the issue?
Yes, it's possible.

#### If so, please list the steps to reproduce below:
1. Delete `config.json` file
2. Duplicate the desired config file and rename it with `config.json`
3. Open ZENZO Core Wallet app and wait until Core Wallet is synchronized
4. Open ZENZO Forge app and wait until Forge is loaded
5. The configuration won't be loaded. Then select the `Setup` button
6. Close and open again ZENZO Core Wallet (as the Forge asks you to do)
7. One of the profiles will be loaded. In my case, it's always `CoinDreams`. Not sure why, but maybe one reason could be because it was the first profile to be created.

### Expected behavior
Forge should let you switch from one profile to another one.

### Actual behavior
Configuration files aren't recognized and the `Setup` button always loads the same profile by default.

### Additional info
The old profiles had this data: `{"wallet":{"user":"user","pass":"forgepass","port":26211,...` and the respective `address`
But the new profile has an associated `user` and `pass`, but no `address`.

### What version of ZENZO Forge are you using?
- Version: v0.5.2
- Commit: N/A
- Type: Official binary

### Machine specs:
- OS: Windows 10 Pro
- CPU: Inter Core i7-7700 @ 3.60GHz
- RAM: 16GB
- Disk size: 250GB
- Disk Type (HD/SDD): SDD

**Comment by JSKitty** [comment]
This issue *should* now be solved by https://github.com/ZENZO-Ecosystem/zenzo-forge/commit/67daff0d20634e3b3b2d19e7f6146cc9582ca089, which re-designs the config system to properly 'mix' settings between ZENZO Core's `zenzo.conf` and ZENZO Forge's `config.json`, it will prioritize the config.json file, but if it contains invalid settings like incorrect RPC User/Pass then the Forge will fallback to using ZENZO Core's direct RPC settings.

Let's see if this is fixed in the next release, re-open the issue if not :D
